In [7]:
from qiskit import QuantumCircuit, transpile
from qiskit_aer import AerSimulator
import numpy as np

In [2]:
backend = AerSimulator()

Following cell shows that 'get_counts' must be read backwards.
i.e. Qubit 0 is mapped to result_string[::-1][0]

In [6]:
qc = QuantumCircuit(4)
qc.x(0)
qc.x(2)
qc.measure_all()
result = backend.run(qc).result()
result.get_counts()

{'0101': 1024}

Following cell shows that a statevector index is built from a result_string as sum(2^i for i in result_string[::-1]) = sum(2^i if qubit(i) == 1)

In [12]:
qc = QuantumCircuit(4)
qc.x(1)
qc.x(2)
qc.save_statevector('final')
result = backend.run(qc).result()
data = result.data()['final'].data
print(np.nonzero(data))
print(np.binary_repr(np.nonzero(data)[0][0]))

(array([6]),)
110


In [16]:
qc = QuantumCircuit(6)
qc.x(1)
qc.x(2)
qc.x(3)
qc.save_statevector('final')
qc.measure_all()
result = backend.run(qc).result()
data = result.data()['final'].data
print(result.get_counts())
print(np.nonzero(data))
print(np.binary_repr(np.nonzero(data)[0][0]).rjust(6, '0'))

{'001110': 1024}
(array([14]),)
001110


In [22]:
n=3
T = 4
ceil_log_n2 = 3
state_prep_circuit = QuantumCircuit(T * ceil_log_n2)
to_prepare = np.binary_repr(n+1) * T
print(to_prepare)
for i in range(len(to_prepare)):
    if to_prepare[::-1][i] == '1':
        print(i)
        state_prep_circuit.x(i)
state_prep_circuit.save_statevector('final')
state_prep_circuit.measure_all()
result = backend.run(state_prep_circuit).result()
data = result.data()['final'].data
print(result.get_counts())
print(np.nonzero(data))
print(np.binary_repr(np.nonzero(data)[0][0]).rjust(T * ceil_log_n2, '0'))

100100100100
2
5
8
11
{'100100100100': 1024}
(array([2340]),)
100100100100


In [25]:
print(state_prep_circuit.global_phase)
t_circuit = transpile(state_prep_circuit, backend, optimization_level=3)
print(t_circuit.global_phase)

0.0
0.0
